//©2013 Juan Carlos González Amestoy
//Autogenerated file

#import "NSColor+rvmNSColors.h"

@implementation NSColor (rvmNSColors)

+(NSColor*)orangeRed
{
  return [NSColor colorWithRed:1.000000 green:0.270588 blue:0.000000 alpha:1.000000];
}

+(NSColor*)orangeRedWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.270588 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)limeGreen
{
  return [NSColor colorWithRed:0.196078 green:0.803922 blue:0.196078 alpha:1.000000];
}

+(NSColor*)limeGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.196078 green:0.803922 blue:0.196078 alpha:alpha]; 
}

+(NSColor*)springGreen
{
  return [NSColor colorWithRed:0.000000 green:1.000000 blue:0.498039 alpha:1.000000];
}

+(NSColor*)springGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:1.000000 blue:0.498039 alpha:alpha]; 
}

+(NSColor*)blanchedAlmond
{
  return [NSColor colorWithRed:1.000000 green:0.921569 blue:0.803922 alpha:1.000000];
}

+(NSColor*)blanchedAlmondWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.921569 blue:0.803922 alpha:alpha]; 
}

+(NSColor*)mediumBlue
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:0.803922 alpha:1.000000];
}

+(NSColor*)mediumBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:0.803922 alpha:alpha]; 
}

+(NSColor*)sandyBrown
{
  return [NSColor colorWithRed:0.956863 green:0.643137 blue:0.376471 alpha:1.000000];
}

+(NSColor*)sandyBrownWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.956863 green:0.643137 blue:0.376471 alpha:alpha]; 
}

+(NSColor*)paleVioletRed
{
  return [NSColor colorWithRed:0.858824 green:0.439216 blue:0.576471 alpha:1.000000];
}

+(NSColor*)paleVioletRedWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.858824 green:0.439216 blue:0.576471 alpha:alpha]; 
}

+(NSColor*)bisque
{
  return [NSColor colorWithRed:1.000000 green:0.894118 blue:0.768627 alpha:1.000000];
}

+(NSColor*)bisqueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.894118 blue:0.768627 alpha:alpha]; 
}

+(NSColor*)gainsboro
{
  return [NSColor colorWithRed:0.862745 green:0.862745 blue:0.862745 alpha:1.000000];
}

+(NSColor*)gainsboroWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.862745 green:0.862745 blue:0.862745 alpha:alpha]; 
}

+(NSColor*)royalBlue
{
  return [NSColor colorWithRed:0.254902 green:0.411765 blue:0.882353 alpha:1.000000];
}

+(NSColor*)royalBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.254902 green:0.411765 blue:0.882353 alpha:alpha]; 
}

+(NSColor*)orange
{
  return [NSColor colorWithRed:1.000000 green:0.647059 blue:0.000000 alpha:1.000000];
}

+(NSColor*)orangeWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.647059 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)indianRed
{
  return [NSColor colorWithRed:0.803922 green:0.360784 blue:0.360784 alpha:1.000000];
}

+(NSColor*)indianRedWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.803922 green:0.360784 blue:0.360784 alpha:alpha]; 
}

+(NSColor*)gold
{
  return [NSColor colorWithRed:1.000000 green:0.843137 blue:0.000000 alpha:1.000000];
}

+(NSColor*)goldWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.843137 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)powderBlue
{
  return [NSColor colorWithRed:0.690196 green:0.878431 blue:0.901961 alpha:1.000000];
}

+(NSColor*)powderBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.690196 green:0.878431 blue:0.901961 alpha:alpha]; 
}

+(NSColor*)burlyWood
{
  return [NSColor colorWithRed:0.870588 green:0.721569 blue:0.529412 alpha:1.000000];
}

+(NSColor*)burlyWoodWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.870588 green:0.721569 blue:0.529412 alpha:alpha]; 
}

+(NSColor*)azure
{
  return [NSColor colorWithRed:0.941176 green:1.000000 blue:1.000000 alpha:1.000000];
}

+(NSColor*)azureWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.941176 green:1.000000 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)oliveDrab
{
  return [NSColor colorWithRed:0.419608 green:0.556863 blue:0.137255 alpha:1.000000];
}

+(NSColor*)oliveDrabWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.419608 green:0.556863 blue:0.137255 alpha:alpha]; 
}

+(NSColor*)mediumSeaGreen
{
  return [NSColor colorWithRed:0.235294 green:0.701961 blue:0.443137 alpha:1.000000];
}

+(NSColor*)mediumSeaGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.235294 green:0.701961 blue:0.443137 alpha:alpha]; 
}

+(NSColor*)green
{
  return [NSColor colorWithRed:0.000000 green:0.501961 blue:0.000000 alpha:1.000000];
}

+(NSColor*)greenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.501961 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)slateBlue
{
  return [NSColor colorWithRed:0.415686 green:0.352941 blue:0.803922 alpha:1.000000];
}

+(NSColor*)slateBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.415686 green:0.352941 blue:0.803922 alpha:alpha]; 
}

+(NSColor*)olive
{
  return [NSColor colorWithRed:0.501961 green:0.501961 blue:0.000000 alpha:1.000000];
}

+(NSColor*)oliveWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.501961 green:0.501961 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)blueViolet
{
  return [NSColor colorWithRed:0.541176 green:0.168627 blue:0.886275 alpha:1.000000];
}

+(NSColor*)blueVioletWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.541176 green:0.168627 blue:0.886275 alpha:alpha]; 
}

+(NSColor*)snow
{
  return [NSColor colorWithRed:1.000000 green:0.980392 blue:0.980392 alpha:1.000000];
}

+(NSColor*)snowWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.980392 blue:0.980392 alpha:alpha]; 
}

+(NSColor*)navy
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:0.501961 alpha:1.000000];
}

+(NSColor*)navyWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:0.501961 alpha:alpha]; 
}

+(NSColor*)mediumVioletRed
{
  return [NSColor colorWithRed:0.780392 green:0.082353 blue:0.521569 alpha:1.000000];
}

+(NSColor*)mediumVioletRedWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.780392 green:0.082353 blue:0.521569 alpha:alpha]; 
}

+(NSColor*)dimGray
{
  return [NSColor colorWithRed:0.411765 green:0.411765 blue:0.411765 alpha:1.000000];
}

+(NSColor*)dimGrayWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.411765 green:0.411765 blue:0.411765 alpha:alpha]; 
}

+(NSColor*)floralWhite
{
  return [NSColor colorWithRed:1.000000 green:0.980392 blue:0.941176 alpha:1.000000];
}

+(NSColor*)floralWhiteWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.980392 blue:0.941176 alpha:alpha]; 
}

+(NSColor*)crimson
{
  return [NSColor colorWithRed:0.862745 green:0.078431 blue:0.235294 alpha:1.000000];
}

+(NSColor*)crimsonWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.862745 green:0.078431 blue:0.235294 alpha:alpha]; 
}

+(NSColor*)darkSalmon
{
  return [NSColor colorWithRed:0.913725 green:0.588235 blue:0.478431 alpha:1.000000];
}

+(NSColor*)darkSalmonWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.913725 green:0.588235 blue:0.478431 alpha:alpha]; 
}

+(NSColor*)mintCream
{
  return [NSColor colorWithRed:0.960784 green:1.000000 blue:0.980392 alpha:1.000000];
}

+(NSColor*)mintCreamWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.960784 green:1.000000 blue:0.980392 alpha:alpha]; 
}

+(NSColor*)darkGreen
{
  return [NSColor colorWithRed:0.000000 green:0.392157 blue:0.000000 alpha:1.000000];
}

+(NSColor*)darkGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.392157 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)mediumSpringGreen
{
  return [NSColor colorWithRed:0.000000 green:0.980392 blue:0.603922 alpha:1.000000];
}

+(NSColor*)mediumSpringGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.980392 blue:0.603922 alpha:alpha]; 
}

+(NSColor*)oldLace
{
  return [NSColor colorWithRed:0.992157 green:0.960784 blue:0.901961 alpha:1.000000];
}

+(NSColor*)oldLaceWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.992157 green:0.960784 blue:0.901961 alpha:alpha]; 
}

+(NSColor*)darkSlateBlue
{
  return [NSColor colorWithRed:0.282353 green:0.239216 blue:0.545098 alpha:1.000000];
}

+(NSColor*)darkSlateBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.282353 green:0.239216 blue:0.545098 alpha:alpha]; 
}

+(NSColor*)indigo
{
  return [NSColor colorWithRed:0.294118 green:0.000000 blue:0.509804 alpha:1.000000];
}

+(NSColor*)indigoWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.294118 green:0.000000 blue:0.509804 alpha:alpha]; 
}

+(NSColor*)cornflowerBlue
{
  return [NSColor colorWithRed:0.392157 green:0.584314 blue:0.929412 alpha:1.000000];
}

+(NSColor*)cornflowerBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.392157 green:0.584314 blue:0.929412 alpha:alpha]; 
}

+(NSColor*)fireBrick
{
  return [NSColor colorWithRed:0.698039 green:0.133333 blue:0.133333 alpha:1.000000];
}

+(NSColor*)fireBrickWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.698039 green:0.133333 blue:0.133333 alpha:alpha]; 
}

+(NSColor*)midnightBlue
{
  return [NSColor colorWithRed:0.098039 green:0.098039 blue:0.439216 alpha:1.000000];
}

+(NSColor*)midnightBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.098039 green:0.098039 blue:0.439216 alpha:alpha]; 
}

+(NSColor*)honeydew
{
  return [NSColor colorWithRed:0.941176 green:1.000000 blue:0.941176 alpha:1.000000];
}

+(NSColor*)honeydewWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.941176 green:1.000000 blue:0.941176 alpha:alpha]; 
}

+(NSColor*)papayaWhip
{
  return [NSColor colorWithRed:1.000000 green:0.937255 blue:0.835294 alpha:1.000000];
}

+(NSColor*)papayaWhipWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.937255 blue:0.835294 alpha:alpha]; 
}

+(NSColor*)darkBlue
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:0.545098 alpha:1.000000];
}

+(NSColor*)darkBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:0.545098 alpha:alpha]; 
}

+(NSColor*)ghostWhite
{
  return [NSColor colorWithRed:0.972549 green:0.972549 blue:1.000000 alpha:1.000000];
}

+(NSColor*)ghostWhiteWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.972549 green:0.972549 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)darkOrchid
{
  return [NSColor colorWithRed:0.600000 green:0.196078 blue:0.800000 alpha:1.000000];
}

+(NSColor*)darkOrchidWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.600000 green:0.196078 blue:0.800000 alpha:alpha]; 
}

+(NSColor*)mediumAquamarine
{
  return [NSColor colorWithRed:0.400000 green:0.803922 blue:0.666667 alpha:1.000000];
}

+(NSColor*)mediumAquamarineWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.400000 green:0.803922 blue:0.666667 alpha:alpha]; 
}

+(NSColor*)thistle
{
  return [NSColor colorWithRed:0.847059 green:0.749020 blue:0.847059 alpha:1.000000];
}

+(NSColor*)thistleWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.847059 green:0.749020 blue:0.847059 alpha:alpha]; 
}

+(NSColor*)ivory
{
  return [NSColor colorWithRed:1.000000 green:1.000000 blue:0.941176 alpha:1.000000];
}

+(NSColor*)ivoryWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:1.000000 blue:0.941176 alpha:alpha]; 
}

+(NSColor*)blue
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:1.000000];
}

+(NSColor*)blueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)lightCyan
{
  return [NSColor colorWithRed:0.878431 green:1.000000 blue:1.000000 alpha:1.000000];
}

+(NSColor*)lightCyanWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.878431 green:1.000000 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)aliceBlue
{
  return [NSColor colorWithRed:0.941176 green:0.972549 blue:1.000000 alpha:1.000000];
}

+(NSColor*)aliceBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.941176 green:0.972549 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)red
{
  return [NSColor colorWithRed:1.000000 green:0.000000 blue:0.000000 alpha:1.000000];
}

+(NSColor*)redWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.000000 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)goldenrod
{
  return [NSColor colorWithRed:0.854902 green:0.647059 blue:0.125490 alpha:1.000000];
}

+(NSColor*)goldenrodWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.854902 green:0.647059 blue:0.125490 alpha:alpha]; 
}

+(NSColor*)saddleBrown
{
  return [NSColor colorWithRed:0.545098 green:0.270588 blue:0.074510 alpha:1.000000];
}

+(NSColor*)saddleBrownWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.545098 green:0.270588 blue:0.074510 alpha:alpha]; 
}

+(NSColor*)yellow
{
  return [NSColor colorWithRed:1.000000 green:1.000000 blue:0.000000 alpha:1.000000];
}

+(NSColor*)yellowWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:1.000000 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)lightBlue
{
  return [NSColor colorWithRed:0.678431 green:0.847059 blue:0.901961 alpha:1.000000];
}

+(NSColor*)lightBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.678431 green:0.847059 blue:0.901961 alpha:alpha]; 
}

+(NSColor*)purple
{
  return [NSColor colorWithRed:0.501961 green:0.000000 blue:0.501961 alpha:1.000000];
}

+(NSColor*)purpleWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.501961 green:0.000000 blue:0.501961 alpha:alpha]; 
}

+(NSColor*)lightSteelBlue
{
  return [NSColor colorWithRed:0.690196 green:0.768627 blue:0.870588 alpha:1.000000];
}

+(NSColor*)lightSteelBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.690196 green:0.768627 blue:0.870588 alpha:alpha]; 
}

+(NSColor*)lightYellow
{
  return [NSColor colorWithRed:1.000000 green:1.000000 blue:0.878431 alpha:1.000000];
}

+(NSColor*)lightYellowWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:1.000000 blue:0.878431 alpha:alpha]; 
}

+(NSColor*)cyan
{
  return [NSColor colorWithRed:0.000000 green:1.000000 blue:1.000000 alpha:1.000000];
}

+(NSColor*)cyanWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:1.000000 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)lemonChiffon
{
  return [NSColor colorWithRed:1.000000 green:0.980392 blue:0.803922 alpha:1.000000];
}

+(NSColor*)lemonChiffonWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.980392 blue:0.803922 alpha:alpha]; 
}

+(NSColor*)darkMagenta
{
  return [NSColor colorWithRed:0.545098 green:0.000000 blue:0.545098 alpha:1.000000];
}

+(NSColor*)darkMagentaWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.545098 green:0.000000 blue:0.545098 alpha:alpha]; 
}

+(NSColor*)lightSeaGreen
{
  return [NSColor colorWithRed:0.125490 green:0.698039 blue:0.666667 alpha:1.000000];
}

+(NSColor*)lightSeaGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.125490 green:0.698039 blue:0.666667 alpha:alpha]; 
}

+(NSColor*)violet
{
  return [NSColor colorWithRed:0.933333 green:0.509804 blue:0.933333 alpha:1.000000];
}

+(NSColor*)violetWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.933333 green:0.509804 blue:0.933333 alpha:alpha]; 
}

+(NSColor*)white
{
  return [NSColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:1.000000];
}

+(NSColor*)whiteWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:1.000000 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)wheat
{
  return [NSColor colorWithRed:0.960784 green:0.870588 blue:0.701961 alpha:1.000000];
}

+(NSColor*)wheatWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.960784 green:0.870588 blue:0.701961 alpha:alpha]; 
}

+(NSColor*)mediumOrchid
{
  return [NSColor colorWithRed:0.729412 green:0.333333 blue:0.827451 alpha:1.000000];
}

+(NSColor*)mediumOrchidWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.729412 green:0.333333 blue:0.827451 alpha:alpha]; 
}

+(NSColor*)paleGoldenrod
{
  return [NSColor colorWithRed:0.933333 green:0.909804 blue:0.666667 alpha:1.000000];
}

+(NSColor*)paleGoldenrodWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.933333 green:0.909804 blue:0.666667 alpha:alpha]; 
}

+(NSColor*)hotPink
{
  return [NSColor colorWithRed:1.000000 green:0.411765 blue:0.705882 alpha:1.000000];
}

+(NSColor*)hotPinkWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.411765 blue:0.705882 alpha:alpha]; 
}

+(NSColor*)dodgerBlue
{
  return [NSColor colorWithRed:0.117647 green:0.564706 blue:1.000000 alpha:1.000000];
}

+(NSColor*)dodgerBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.117647 green:0.564706 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)peru
{
  return [NSColor colorWithRed:0.803922 green:0.521569 blue:0.247059 alpha:1.000000];
}

+(NSColor*)peruWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.803922 green:0.521569 blue:0.247059 alpha:alpha]; 
}

+(NSColor*)lightSkyBlue
{
  return [NSColor colorWithRed:0.529412 green:0.807843 blue:0.980392 alpha:1.000000];
}

+(NSColor*)lightSkyBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.529412 green:0.807843 blue:0.980392 alpha:alpha]; 
}

+(NSColor*)lightPink
{
  return [NSColor colorWithRed:1.000000 green:0.713725 blue:0.756863 alpha:1.000000];
}

+(NSColor*)lightPinkWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.713725 blue:0.756863 alpha:alpha]; 
}

+(NSColor*)darkRed
{
  return [NSColor colorWithRed:0.545098 green:0.000000 blue:0.000000 alpha:1.000000];
}

+(NSColor*)darkRedWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.545098 green:0.000000 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)lightGrey
{
  return [NSColor colorWithRed:0.827451 green:0.827451 blue:0.827451 alpha:1.000000];
}

+(NSColor*)lightGreyWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.827451 green:0.827451 blue:0.827451 alpha:alpha]; 
}

+(NSColor*)turquoise
{
  return [NSColor colorWithRed:0.250980 green:0.878431 blue:0.815686 alpha:1.000000];
}

+(NSColor*)turquoiseWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.250980 green:0.878431 blue:0.815686 alpha:alpha]; 
}

+(NSColor*)deepSkyBlue
{
  return [NSColor colorWithRed:0.000000 green:0.749020 blue:1.000000 alpha:1.000000];
}

+(NSColor*)deepSkyBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.749020 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)sienna
{
  return [NSColor colorWithRed:0.627451 green:0.321569 blue:0.176471 alpha:1.000000];
}

+(NSColor*)siennaWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.627451 green:0.321569 blue:0.176471 alpha:alpha]; 
}

+(NSColor*)lavenderBlush
{
  return [NSColor colorWithRed:1.000000 green:0.941176 blue:0.960784 alpha:1.000000];
}

+(NSColor*)lavenderBlushWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.941176 blue:0.960784 alpha:alpha]; 
}

+(NSColor*)darkGoldenrod
{
  return [NSColor colorWithRed:0.721569 green:0.525490 blue:0.043137 alpha:1.000000];
}

+(NSColor*)darkGoldenrodWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.721569 green:0.525490 blue:0.043137 alpha:alpha]; 
}

+(NSColor*)silver
{
  return [NSColor colorWithRed:0.752941 green:0.752941 blue:0.752941 alpha:1.000000];
}

+(NSColor*)silverWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.752941 green:0.752941 blue:0.752941 alpha:alpha]; 
}

+(NSColor*)antiqueWhite
{
  return [NSColor colorWithRed:0.980392 green:0.921569 blue:0.843137 alpha:1.000000];
}

+(NSColor*)antiqueWhiteWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.980392 green:0.921569 blue:0.843137 alpha:alpha]; 
}

+(NSColor*)chartreuse
{
  return [NSColor colorWithRed:0.498039 green:1.000000 blue:0.000000 alpha:1.000000];
}

+(NSColor*)chartreuseWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.498039 green:1.000000 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)rosyBrown
{
  return [NSColor colorWithRed:0.737255 green:0.560784 blue:0.560784 alpha:1.000000];
}

+(NSColor*)rosyBrownWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.737255 green:0.560784 blue:0.560784 alpha:alpha]; 
}

+(NSColor*)yellowGreen
{
  return [NSColor colorWithRed:0.603922 green:0.803922 blue:0.196078 alpha:1.000000];
}

+(NSColor*)yellowGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.603922 green:0.803922 blue:0.196078 alpha:alpha]; 
}

+(NSColor*)tomato
{
  return [NSColor colorWithRed:1.000000 green:0.388235 blue:0.278431 alpha:1.000000];
}

+(NSColor*)tomatoWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.388235 blue:0.278431 alpha:alpha]; 
}

+(NSColor*)black
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:1.000000];
}

+(NSColor*)blackWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)chocolate
{
  return [NSColor colorWithRed:0.823529 green:0.411765 blue:0.117647 alpha:1.000000];
}

+(NSColor*)chocolateWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.823529 green:0.411765 blue:0.117647 alpha:alpha]; 
}

+(NSColor*)paleGreen
{
  return [NSColor colorWithRed:0.596078 green:0.984314 blue:0.596078 alpha:1.000000];
}

+(NSColor*)paleGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.596078 green:0.984314 blue:0.596078 alpha:alpha]; 
}

+(NSColor*)pink
{
  return [NSColor colorWithRed:1.000000 green:0.752941 blue:0.796078 alpha:1.000000];
}

+(NSColor*)pinkWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.752941 blue:0.796078 alpha:alpha]; 
}

+(NSColor*)darkSlateGray
{
  return [NSColor colorWithRed:0.184314 green:0.309804 blue:0.309804 alpha:1.000000];
}

+(NSColor*)darkSlateGrayWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.184314 green:0.309804 blue:0.309804 alpha:alpha]; 
}

+(NSColor*)slateGray
{
  return [NSColor colorWithRed:0.466667 green:0.533333 blue:0.600000 alpha:1.000000];
}

+(NSColor*)slateGrayWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.466667 green:0.533333 blue:0.600000 alpha:alpha]; 
}

+(NSColor*)aquamarine
{
  return [NSColor colorWithRed:0.498039 green:1.000000 blue:0.831373 alpha:1.000000];
}

+(NSColor*)aquamarineWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.498039 green:1.000000 blue:0.831373 alpha:alpha]; 
}

+(NSColor*)gray
{
  return [NSColor colorWithRed:0.501961 green:0.501961 blue:0.501961 alpha:1.000000];
}

+(NSColor*)grayWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.501961 green:0.501961 blue:0.501961 alpha:alpha]; 
}

+(NSColor*)seaGreen
{
  return [NSColor colorWithRed:0.180392 green:0.545098 blue:0.380392 alpha:1.000000];
}

+(NSColor*)seaGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.180392 green:0.545098 blue:0.380392 alpha:alpha]; 
}

+(NSColor*)coral
{
  return [NSColor colorWithRed:1.000000 green:0.498039 blue:0.313725 alpha:1.000000];
}

+(NSColor*)coralWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.498039 blue:0.313725 alpha:alpha]; 
}

+(NSColor*)mistyRose
{
  return [NSColor colorWithRed:1.000000 green:0.894118 blue:0.882353 alpha:1.000000];
}

+(NSColor*)mistyRoseWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.894118 blue:0.882353 alpha:alpha]; 
}

+(NSColor*)forestGreen
{
  return [NSColor colorWithRed:0.133333 green:0.545098 blue:0.133333 alpha:1.000000];
}

+(NSColor*)forestGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.133333 green:0.545098 blue:0.133333 alpha:alpha]; 
}

+(NSColor*)maroon
{
  return [NSColor colorWithRed:0.501961 green:0.000000 blue:0.000000 alpha:1.000000];
}

+(NSColor*)maroonWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.501961 green:0.000000 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)mediumTurquoise
{
  return [NSColor colorWithRed:0.282353 green:0.819608 blue:0.800000 alpha:1.000000];
}

+(NSColor*)mediumTurquoiseWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.282353 green:0.819608 blue:0.800000 alpha:alpha]; 
}

+(NSColor*)orchid
{
  return [NSColor colorWithRed:0.854902 green:0.439216 blue:0.839216 alpha:1.000000];
}

+(NSColor*)orchidWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.854902 green:0.439216 blue:0.839216 alpha:alpha]; 
}

+(NSColor*)lightGreen
{
  return [NSColor colorWithRed:0.564706 green:0.933333 blue:0.564706 alpha:1.000000];
}

+(NSColor*)lightGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.564706 green:0.933333 blue:0.564706 alpha:alpha]; 
}

+(NSColor*)brown
{
  return [NSColor colorWithRed:0.647059 green:0.164706 blue:0.164706 alpha:1.000000];
}

+(NSColor*)brownWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.647059 green:0.164706 blue:0.164706 alpha:alpha]; 
}

+(NSColor*)whiteSmoke
{
  return [NSColor colorWithRed:0.960784 green:0.960784 blue:0.960784 alpha:1.000000];
}

+(NSColor*)whiteSmokeWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.960784 green:0.960784 blue:0.960784 alpha:alpha]; 
}

+(NSColor*)lightGoldenrodYellow
{
  return [NSColor colorWithRed:0.980392 green:0.980392 blue:0.823529 alpha:1.000000];
}

+(NSColor*)lightGoldenrodYellowWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.980392 green:0.980392 blue:0.823529 alpha:alpha]; 
}

+(NSColor*)darkViolet
{
  return [NSColor colorWithRed:0.580392 green:0.000000 blue:0.827451 alpha:1.000000];
}

+(NSColor*)darkVioletWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.580392 green:0.000000 blue:0.827451 alpha:alpha]; 
}

+(NSColor*)darkTurquoise
{
  return [NSColor colorWithRed:0.000000 green:0.807843 blue:0.819608 alpha:1.000000];
}

+(NSColor*)darkTurquoiseWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.807843 blue:0.819608 alpha:alpha]; 
}

+(NSColor*)lime
{
  return [NSColor colorWithRed:0.000000 green:1.000000 blue:0.000000 alpha:1.000000];
}

+(NSColor*)limeWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:1.000000 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)lightSalmon
{
  return [NSColor colorWithRed:1.000000 green:0.627451 blue:0.478431 alpha:1.000000];
}

+(NSColor*)lightSalmonWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.627451 blue:0.478431 alpha:alpha]; 
}

+(NSColor*)darkSeaGreen
{
  return [NSColor colorWithRed:0.560784 green:0.737255 blue:0.560784 alpha:1.000000];
}

+(NSColor*)darkSeaGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.560784 green:0.737255 blue:0.560784 alpha:alpha]; 
}

+(NSColor*)darkKhaki
{
  return [NSColor colorWithRed:0.741176 green:0.717647 blue:0.419608 alpha:1.000000];
}

+(NSColor*)darkKhakiWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.741176 green:0.717647 blue:0.419608 alpha:alpha]; 
}

+(NSColor*)steelBlue
{
  return [NSColor colorWithRed:0.274510 green:0.509804 blue:0.705882 alpha:1.000000];
}

+(NSColor*)steelBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.274510 green:0.509804 blue:0.705882 alpha:alpha]; 
}

+(NSColor*)peachPuff
{
  return [NSColor colorWithRed:1.000000 green:0.854902 blue:0.725490 alpha:1.000000];
}

+(NSColor*)peachPuffWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.854902 blue:0.725490 alpha:alpha]; 
}

+(NSColor*)magenta
{
  return [NSColor colorWithRed:1.000000 green:0.000000 blue:1.000000 alpha:1.000000];
}

+(NSColor*)magentaWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.000000 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)salmon
{
  return [NSColor colorWithRed:0.980392 green:0.501961 blue:0.447059 alpha:1.000000];
}

+(NSColor*)salmonWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.980392 green:0.501961 blue:0.447059 alpha:alpha]; 
}

+(NSColor*)darkCyan
{
  return [NSColor colorWithRed:0.000000 green:0.545098 blue:0.545098 alpha:1.000000];
}

+(NSColor*)darkCyanWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.545098 blue:0.545098 alpha:alpha]; 
}

+(NSColor*)greenYellow
{
  return [NSColor colorWithRed:0.678431 green:1.000000 blue:0.184314 alpha:1.000000];
}

+(NSColor*)greenYellowWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.678431 green:1.000000 blue:0.184314 alpha:alpha]; 
}

+(NSColor*)beige
{
  return [NSColor colorWithRed:0.960784 green:0.960784 blue:0.862745 alpha:1.000000];
}

+(NSColor*)beigeWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.960784 green:0.960784 blue:0.862745 alpha:alpha]; 
}

+(NSColor*)lavender
{
  return [NSColor colorWithRed:0.901961 green:0.901961 blue:0.980392 alpha:1.000000];
}

+(NSColor*)lavenderWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.901961 green:0.901961 blue:0.980392 alpha:alpha]; 
}

+(NSColor*)cadetBlue
{
  return [NSColor colorWithRed:0.372549 green:0.619608 blue:0.627451 alpha:1.000000];
}

+(NSColor*)cadetBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.372549 green:0.619608 blue:0.627451 alpha:alpha]; 
}

+(NSColor*)darkGray
{
  return [NSColor colorWithRed:0.662745 green:0.662745 blue:0.662745 alpha:1.000000];
}

+(NSColor*)darkGrayWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.662745 green:0.662745 blue:0.662745 alpha:alpha]; 
}

+(NSColor*)lawnGreen
{
  return [NSColor colorWithRed:0.486275 green:0.988235 blue:0.000000 alpha:1.000000];
}

+(NSColor*)lawnGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.486275 green:0.988235 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)seashell
{
  return [NSColor colorWithRed:1.000000 green:0.960784 blue:0.933333 alpha:1.000000];
}

+(NSColor*)seashellWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.960784 blue:0.933333 alpha:alpha]; 
}

+(NSColor*)skyBlue
{
  return [NSColor colorWithRed:0.529412 green:0.807843 blue:0.921569 alpha:1.000000];
}

+(NSColor*)skyBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.529412 green:0.807843 blue:0.921569 alpha:alpha]; 
}

+(NSColor*)aqua
{
  return [NSColor colorWithRed:0.000000 green:1.000000 blue:1.000000 alpha:1.000000];
}

+(NSColor*)aquaWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:1.000000 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)deepPink
{
  return [NSColor colorWithRed:1.000000 green:0.078431 blue:0.576471 alpha:1.000000];
}

+(NSColor*)deepPinkWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.078431 blue:0.576471 alpha:alpha]; 
}

+(NSColor*)paleTurquoise
{
  return [NSColor colorWithRed:0.686275 green:0.933333 blue:0.933333 alpha:1.000000];
}

+(NSColor*)paleTurquoiseWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.686275 green:0.933333 blue:0.933333 alpha:alpha]; 
}

+(NSColor*)lightSlateGray
{
  return [NSColor colorWithRed:0.466667 green:0.533333 blue:0.600000 alpha:1.000000];
}

+(NSColor*)lightSlateGrayWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.466667 green:0.533333 blue:0.600000 alpha:alpha]; 
}

+(NSColor*)plum
{
  return [NSColor colorWithRed:0.866667 green:0.627451 blue:0.866667 alpha:1.000000];
}

+(NSColor*)plumWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.866667 green:0.627451 blue:0.866667 alpha:alpha]; 
}

+(NSColor*)mediumPurple
{
  return [NSColor colorWithRed:0.576471 green:0.439216 blue:0.858824 alpha:1.000000];
}

+(NSColor*)mediumPurpleWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.576471 green:0.439216 blue:0.858824 alpha:alpha]; 
}

+(NSColor*)navajoWhite
{
  return [NSColor colorWithRed:1.000000 green:0.870588 blue:0.678431 alpha:1.000000];
}

+(NSColor*)navajoWhiteWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.870588 blue:0.678431 alpha:alpha]; 
}

+(NSColor*)linen
{
  return [NSColor colorWithRed:0.980392 green:0.941176 blue:0.901961 alpha:1.000000];
}

+(NSColor*)linenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.980392 green:0.941176 blue:0.901961 alpha:alpha]; 
}

+(NSColor*)transparent
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:0.000000];
}

+(NSColor*)transparentWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.000000 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)khaki
{
  return [NSColor colorWithRed:0.941176 green:0.901961 blue:0.549020 alpha:1.000000];
}

+(NSColor*)khakiWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.941176 green:0.901961 blue:0.549020 alpha:alpha]; 
}

+(NSColor*)darkOrange
{
  return [NSColor colorWithRed:1.000000 green:0.549020 blue:0.000000 alpha:1.000000];
}

+(NSColor*)darkOrangeWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.549020 blue:0.000000 alpha:alpha]; 
}

+(NSColor*)teal
{
  return [NSColor colorWithRed:0.000000 green:0.501961 blue:0.501961 alpha:1.000000];
}

+(NSColor*)tealWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.000000 green:0.501961 blue:0.501961 alpha:alpha]; 
}

+(NSColor*)fuchsia
{
  return [NSColor colorWithRed:1.000000 green:0.000000 blue:1.000000 alpha:1.000000];
}

+(NSColor*)fuchsiaWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.000000 blue:1.000000 alpha:alpha]; 
}

+(NSColor*)lightCoral
{
  return [NSColor colorWithRed:0.941176 green:0.501961 blue:0.501961 alpha:1.000000];
}

+(NSColor*)lightCoralWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.941176 green:0.501961 blue:0.501961 alpha:alpha]; 
}

+(NSColor*)cornsilk
{
  return [NSColor colorWithRed:0.882353 green:0.972549 blue:0.862745 alpha:1.000000];
}

+(NSColor*)cornsilkWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.882353 green:0.972549 blue:0.862745 alpha:alpha]; 
}

+(NSColor*)tan
{
  return [NSColor colorWithRed:0.823529 green:0.705882 blue:0.549020 alpha:1.000000];
}

+(NSColor*)tanWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.823529 green:0.705882 blue:0.549020 alpha:alpha]; 
}

+(NSColor*)moccasin
{
  return [NSColor colorWithRed:1.000000 green:0.894118 blue:0.709804 alpha:1.000000];
}

+(NSColor*)moccasinWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:1.000000 green:0.894118 blue:0.709804 alpha:alpha]; 
}

+(NSColor*)darkOliveGreen
{
  return [NSColor colorWithRed:0.333333 green:0.419608 blue:0.184314 alpha:1.000000];
}

+(NSColor*)darkOliveGreenWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.333333 green:0.419608 blue:0.184314 alpha:alpha]; 
}

+(NSColor*)mediumSlateBlue
{
  return [NSColor colorWithRed:0.482353 green:0.407843 blue:0.933333 alpha:1.000000];
}

+(NSColor*)mediumSlateBlueWithAlpha:(double)alpha
{
  return [NSColor colorWithRed:0.482353 green:0.407843 blue:0.933333 alpha:alpha]; 
}



@end

