--©2013 Juan Carlos González Amestoy

require('h.string')
local params=require('tools.misc.params')
local file=require('h.io.file')
local util=require('h.text.util')
local bit=require('bit')

local p=params.new()

local lines={[[
//©2013 Juan Carlos González Amestoy
//File autogenerated.
]]}

local linesH={[[
//©2013 Juan Carlos González Amestoy
//File autogenerated.
]]}

local f=file.dir(arg[1])

for k,v in pairs(f) do
	if v.path:ends('.glsl') then
		local s={}

		local fi=file.open(v.path,"r")
		local str=fi:readAll()
		fi:close()

		for i=1,#str,1 do
			s[#s+1]=util.format('0x%s',bit.tohex(string.byte(str,i),2))
		end

		s[#s+1]='0x00'
		s=table.concat(s,',')
		lines[#lines+1]=util.format("const char rvmShader_%s[]={%s};",v.name(0,-5),s)	
    linesH[#linesH+1]=util.format("extern const char rvmShader_%s[];",v.name(0,-5))
	end
end

file.writeLines('rvmShaders.h',linesH)
file.writeLines('rvmShaders.c',lines)
