//©2013 Juan Carlos González Amestoy
//File autogenerated.

extern const char rvmShader_crtFS[];
extern const char rvmShader_crtPlus[];
extern const char rvmShader_normalFS[];
extern const char rvmShader_normalVS[];
extern const char rvmShader_paused[];
extern const char rvmShader_plasma[];
extern const char rvmShader_warp[];
extern const char rvmShader_whiteNoise[];
